package Game.Main;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.AbstractMap.SimpleEntry;
import java.util.Arrays;
import java.util.List;
import java.util.Map.Entry;

import javax.swing.JButton;
import javax.swing.JPanel;

public class Level extends JPanel {

  private static final String[] LEVEL_MAPS = {
    "src/Resource/Map/Map 1.txt",
    "src/Resource/Map/Map 2.txt",
    "src/Resource/Map/Map 3.txt",
    "src/Resource/Map/Map 4.txt",
    "src/Resource/Map/Map 5.txt",
  };

  private static final List<List<List<Entry<Integer, Integer>>>> ROUTES = Arrays.asList(
    // Road map 1
    Arrays.asList(
      Arrays.asList(
        new SimpleEntry<Integer, Integer>(1, 7),
        new SimpleEntry<Integer, Integer>(2, 7),
        new SimpleEntry<Integer, Integer>(3, 7),
        new SimpleEntry<Integer, Integer>(4, 7),
        new SimpleEntry<Integer, Integer>(5, 7),
        new SimpleEntry<Integer, Integer>(6, 7),
        new SimpleEntry<Integer, Integer>(7, 7),
        new SimpleEntry<Integer, Integer>(8, 7),
        new SimpleEntry<Integer, Integer>(9, 7),
        new SimpleEntry<Integer, Integer>(10, 7),
        new SimpleEntry<Integer, Integer>(11, 7),
        new SimpleEntry<Integer, Integer>(12, 7),
        new SimpleEntry<Integer, Integer>(13, 7),
        new SimpleEntry<Integer, Integer>(14, 7),
        new SimpleEntry<Integer, Integer>(15, 7),
        new SimpleEntry<Integer, Integer>(16, 7),
        new SimpleEntry<Integer, Integer>(17, 7),
        new SimpleEntry<Integer, Integer>(18, 7),
        new SimpleEntry<Integer, Integer>(19, 7),
        new SimpleEntry<Integer, Integer>(20, 7),
        new SimpleEntry<Integer, Integer>(21, 7),
        new SimpleEntry<Integer, Integer>(22, 7),
        new SimpleEntry<Integer, Integer>(23, 7),
        new SimpleEntry<Integer, Integer>(24, 7),
        new SimpleEntry<Integer, Integer>(25, 7),
        new SimpleEntry<Integer, Integer>(26, 7),
        new SimpleEntry<Integer, Integer>(27, 7),
        new SimpleEntry<Integer, Integer>(28, 7)
      )
    ),
    // Road map 2
    Arrays.asList(
      Arrays.asList(
        new SimpleEntry<Integer, Integer>(1, 7),
        new SimpleEntry<Integer, Integer>(2, 7),
        new SimpleEntry<Integer, Integer>(3, 7),
        new SimpleEntry<Integer, Integer>(3, 6),
        new SimpleEntry<Integer, Integer>(3, 5),
        new SimpleEntry<Integer, Integer>(3, 4),
        new SimpleEntry<Integer, Integer>(3, 3),
        new SimpleEntry<Integer, Integer>(3, 2),
        new SimpleEntry<Integer, Integer>(4, 2),
        new SimpleEntry<Integer, Integer>(5, 2),
        new SimpleEntry<Integer, Integer>(5, 3),
        new SimpleEntry<Integer, Integer>(5, 4),
        new SimpleEntry<Integer, Integer>(5, 5),
        new SimpleEntry<Integer, Integer>(5, 6),
        new SimpleEntry<Integer, Integer>(5, 7),
        new SimpleEntry<Integer, Integer>(5, 8),
        new SimpleEntry<Integer, Integer>(5, 9),
        new SimpleEntry<Integer, Integer>(5, 10),
        new SimpleEntry<Integer, Integer>(5, 11),
        new SimpleEntry<Integer, Integer>(5, 12),
        new SimpleEntry<Integer, Integer>(5, 13),
        new SimpleEntry<Integer, Integer>(6, 13),
        new SimpleEntry<Integer, Integer>(7, 13),
        new SimpleEntry<Integer, Integer>(7, 12),
        new SimpleEntry<Integer, Integer>(7, 11),
        new SimpleEntry<Integer, Integer>(7, 10),
        new SimpleEntry<Integer, Integer>(7, 9),
        new SimpleEntry<Integer, Integer>(7, 8),
        new SimpleEntry<Integer, Integer>(7, 7),
        new SimpleEntry<Integer, Integer>(7, 6),
        new SimpleEntry<Integer, Integer>(7, 5),
        new SimpleEntry<Integer, Integer>(7, 4),
        new SimpleEntry<Integer, Integer>(7, 3),
        new SimpleEntry<Integer, Integer>(7, 2),
        new SimpleEntry<Integer, Integer>(8, 2),
        new SimpleEntry<Integer, Integer>(9, 2),
        new SimpleEntry<Integer, Integer>(9, 3),
        new SimpleEntry<Integer, Integer>(9, 4),
        new SimpleEntry<Integer, Integer>(9, 5),
        new SimpleEntry<Integer, Integer>(9, 6),
        new SimpleEntry<Integer, Integer>(9, 7),
        new SimpleEntry<Integer, Integer>(9, 8),
        new SimpleEntry<Integer, Integer>(9, 9),
        new SimpleEntry<Integer, Integer>(9, 10),
        new SimpleEntry<Integer, Integer>(9, 11),
        new SimpleEntry<Integer, Integer>(9, 12),
        new SimpleEntry<Integer, Integer>(9, 13),
        new SimpleEntry<Integer, Integer>(10, 13),
        new SimpleEntry<Integer, Integer>(11, 13),
        new SimpleEntry<Integer, Integer>(11, 12),
        new SimpleEntry<Integer, Integer>(11, 11),
        new SimpleEntry<Integer, Integer>(11, 10),
        new SimpleEntry<Integer, Integer>(11, 9),
        new SimpleEntry<Integer, Integer>(11, 8),
        new SimpleEntry<Integer, Integer>(11, 7),
        new SimpleEntry<Integer, Integer>(11, 6),
        new SimpleEntry<Integer, Integer>(11, 5),
        new SimpleEntry<Integer, Integer>(11, 4),
        new SimpleEntry<Integer, Integer>(11, 3),
        new SimpleEntry<Integer, Integer>(11, 2),
        new SimpleEntry<Integer, Integer>(12, 2),
        new SimpleEntry<Integer, Integer>(13, 2),
        new SimpleEntry<Integer, Integer>(13, 3),
        new SimpleEntry<Integer, Integer>(13, 4),
        new SimpleEntry<Integer, Integer>(13, 5),
        new SimpleEntry<Integer, Integer>(13, 6),
        new SimpleEntry<Integer, Integer>(13, 7),
        new SimpleEntry<Integer, Integer>(13, 8),
        new SimpleEntry<Integer, Integer>(13, 9),
        new SimpleEntry<Integer, Integer>(13, 10),
        new SimpleEntry<Integer, Integer>(13, 11),
        new SimpleEntry<Integer, Integer>(13, 12),
        new SimpleEntry<Integer, Integer>(13, 13),
        new SimpleEntry<Integer, Integer>(14, 13),
        new SimpleEntry<Integer, Integer>(15, 13),
        new SimpleEntry<Integer, Integer>(15, 12),
        new SimpleEntry<Integer, Integer>(15, 11),
        new SimpleEntry<Integer, Integer>(15, 10),
        new SimpleEntry<Integer, Integer>(15, 9),
        new SimpleEntry<Integer, Integer>(15, 8),
        new SimpleEntry<Integer, Integer>(15, 7),
        new SimpleEntry<Integer, Integer>(15, 6),
        new SimpleEntry<Integer, Integer>(15, 5),
        new SimpleEntry<Integer, Integer>(15, 4),
        new SimpleEntry<Integer, Integer>(15, 3),
        new SimpleEntry<Integer, Integer>(15, 2),
        new SimpleEntry<Integer, Integer>(16, 2),
        new SimpleEntry<Integer, Integer>(17, 2),
        new SimpleEntry<Integer, Integer>(17, 3),
        new SimpleEntry<Integer, Integer>(17, 4),
        new SimpleEntry<Integer, Integer>(17, 5),
        new SimpleEntry<Integer, Integer>(17, 6),
        new SimpleEntry<Integer, Integer>(17, 7),
        new SimpleEntry<Integer, Integer>(17, 8),
        new SimpleEntry<Integer, Integer>(17, 9),
        new SimpleEntry<Integer, Integer>(17, 10),
        new SimpleEntry<Integer, Integer>(17, 11),
        new SimpleEntry<Integer, Integer>(17, 12),
        new SimpleEntry<Integer, Integer>(17, 13),
        new SimpleEntry<Integer, Integer>(18, 13),
        new SimpleEntry<Integer, Integer>(19, 13),
        new SimpleEntry<Integer, Integer>(19, 12),
        new SimpleEntry<Integer, Integer>(19, 11),
        new SimpleEntry<Integer, Integer>(19, 10),
        new SimpleEntry<Integer, Integer>(19, 9),
        new SimpleEntry<Integer, Integer>(19, 8),
        new SimpleEntry<Integer, Integer>(19, 7),
        new SimpleEntry<Integer, Integer>(19, 6),
        new SimpleEntry<Integer, Integer>(19, 5),
        new SimpleEntry<Integer, Integer>(19, 4),
        new SimpleEntry<Integer, Integer>(19, 3),
        new SimpleEntry<Integer, Integer>(19, 2),
        new SimpleEntry<Integer, Integer>(20, 2),
        new SimpleEntry<Integer, Integer>(21, 2),
        new SimpleEntry<Integer, Integer>(21, 3),
        new SimpleEntry<Integer, Integer>(21, 4),
        new SimpleEntry<Integer, Integer>(21, 5),
        new SimpleEntry<Integer, Integer>(21, 6),
        new SimpleEntry<Integer, Integer>(21, 7),
        new SimpleEntry<Integer, Integer>(21, 8),
        new SimpleEntry<Integer, Integer>(21, 9),
        new SimpleEntry<Integer, Integer>(21, 10),
        new SimpleEntry<Integer, Integer>(21, 11),
        new SimpleEntry<Integer, Integer>(21, 12),
        new SimpleEntry<Integer, Integer>(21, 13),
        new SimpleEntry<Integer, Integer>(22, 13),
        new SimpleEntry<Integer, Integer>(23, 13),
        new SimpleEntry<Integer, Integer>(23, 12),
        new SimpleEntry<Integer, Integer>(23, 11),
        new SimpleEntry<Integer, Integer>(23, 10),
        new SimpleEntry<Integer, Integer>(23, 9),
        new SimpleEntry<Integer, Integer>(23, 8),
        new SimpleEntry<Integer, Integer>(23, 7),
        new SimpleEntry<Integer, Integer>(23, 6),
        new SimpleEntry<Integer, Integer>(23, 5),
        new SimpleEntry<Integer, Integer>(23, 4),
        new SimpleEntry<Integer, Integer>(23, 3),
        new SimpleEntry<Integer, Integer>(23, 2),
        new SimpleEntry<Integer, Integer>(24, 2),
        new SimpleEntry<Integer, Integer>(25, 2),
        new SimpleEntry<Integer, Integer>(25, 3),
        new SimpleEntry<Integer, Integer>(25, 4),
        new SimpleEntry<Integer, Integer>(25, 5),
        new SimpleEntry<Integer, Integer>(25, 6),
        new SimpleEntry<Integer, Integer>(25, 7),
        new SimpleEntry<Integer, Integer>(25, 8),
        new SimpleEntry<Integer, Integer>(25, 9),
        new SimpleEntry<Integer, Integer>(25, 10),
        new SimpleEntry<Integer, Integer>(25, 11),
        new SimpleEntry<Integer, Integer>(25, 12),
        new SimpleEntry<Integer, Integer>(25, 13),
        new SimpleEntry<Integer, Integer>(26, 13),
        new SimpleEntry<Integer, Integer>(27, 13),
        new SimpleEntry<Integer, Integer>(27, 12),
        new SimpleEntry<Integer, Integer>(27, 11),
        new SimpleEntry<Integer, Integer>(27, 10),
        new SimpleEntry<Integer, Integer>(27, 9),
        new SimpleEntry<Integer, Integer>(27, 8),
        new SimpleEntry<Integer, Integer>(27, 7),
        new SimpleEntry<Integer, Integer>(28, 7)
      )
    ),
    // Road map 3
    Arrays.asList(
      Arrays.asList(
        new SimpleEntry<Integer, Integer>(2, 7),
        new SimpleEntry<Integer, Integer>(2, 8),
        new SimpleEntry<Integer, Integer>(2, 9),
        new SimpleEntry<Integer, Integer>(2, 10),
        new SimpleEntry<Integer, Integer>(2, 11),
        new SimpleEntry<Integer, Integer>(2, 12),
        new SimpleEntry<Integer, Integer>(2, 13),
        new SimpleEntry<Integer, Integer>(3, 13),
        new SimpleEntry<Integer, Integer>(3, 13),
        new SimpleEntry<Integer, Integer>(5, 13),
        new SimpleEntry<Integer, Integer>(6, 13),
        new SimpleEntry<Integer, Integer>(7, 13),
        new SimpleEntry<Integer, Integer>(8, 13),
        new SimpleEntry<Integer, Integer>(9, 13),
        new SimpleEntry<Integer, Integer>(10, 13),
        new SimpleEntry<Integer, Integer>(11, 13),
        new SimpleEntry<Integer, Integer>(12, 13),
        new SimpleEntry<Integer, Integer>(13, 13),
        new SimpleEntry<Integer, Integer>(14, 13),
        new SimpleEntry<Integer, Integer>(15, 13),
        new SimpleEntry<Integer, Integer>(16, 13),
        new SimpleEntry<Integer, Integer>(17, 13),
        new SimpleEntry<Integer, Integer>(18, 13),
        new SimpleEntry<Integer, Integer>(19, 13),
        new SimpleEntry<Integer, Integer>(20, 13),
        new SimpleEntry<Integer, Integer>(21, 13),
        new SimpleEntry<Integer, Integer>(22, 13),
        new SimpleEntry<Integer, Integer>(23, 13),
        new SimpleEntry<Integer, Integer>(24, 13),
        new SimpleEntry<Integer, Integer>(25, 13),
        new SimpleEntry<Integer, Integer>(26, 13),
        new SimpleEntry<Integer, Integer>(27, 13),
        new SimpleEntry<Integer, Integer>(27, 13),
        new SimpleEntry<Integer, Integer>(27, 12),
        new SimpleEntry<Integer, Integer>(27, 11),
        new SimpleEntry<Integer, Integer>(27, 10),
        new SimpleEntry<Integer, Integer>(27, 9),
        new SimpleEntry<Integer, Integer>(27, 8),
        new SimpleEntry<Integer, Integer>(27, 7)
      ),
      Arrays.asList(
        new SimpleEntry<Integer, Integer>(2, 7),
        new SimpleEntry<Integer, Integer>(2, 6),
        new SimpleEntry<Integer, Integer>(2, 5),
        new SimpleEntry<Integer, Integer>(2, 4),
        new SimpleEntry<Integer, Integer>(2, 3),
        new SimpleEntry<Integer, Integer>(2, 2),
        new SimpleEntry<Integer, Integer>(3, 2),
        new SimpleEntry<Integer, Integer>(3, 2),
        new SimpleEntry<Integer, Integer>(5, 2),
        new SimpleEntry<Integer, Integer>(6, 2),
        new SimpleEntry<Integer, Integer>(7, 2),
        new SimpleEntry<Integer, Integer>(8, 2),
        new SimpleEntry<Integer, Integer>(9, 2),
        new SimpleEntry<Integer, Integer>(10, 2),
        new SimpleEntry<Integer, Integer>(11, 2),
        new SimpleEntry<Integer, Integer>(12, 2),
        new SimpleEntry<Integer, Integer>(13, 2),
        new SimpleEntry<Integer, Integer>(14, 2),
        new SimpleEntry<Integer, Integer>(15, 2),
        new SimpleEntry<Integer, Integer>(16, 2),
        new SimpleEntry<Integer, Integer>(17, 2),
        new SimpleEntry<Integer, Integer>(18, 2),
        new SimpleEntry<Integer, Integer>(19, 2),
        new SimpleEntry<Integer, Integer>(20, 2),
        new SimpleEntry<Integer, Integer>(21, 2),
        new SimpleEntry<Integer, Integer>(22, 2),
        new SimpleEntry<Integer, Integer>(23, 2),
        new SimpleEntry<Integer, Integer>(24, 2),
        new SimpleEntry<Integer, Integer>(25, 2),
        new SimpleEntry<Integer, Integer>(26, 2),
        new SimpleEntry<Integer, Integer>(27, 2),
        new SimpleEntry<Integer, Integer>(27, 2),
        new SimpleEntry<Integer, Integer>(27, 3),
        new SimpleEntry<Integer, Integer>(27, 4),
        new SimpleEntry<Integer, Integer>(27, 5),
        new SimpleEntry<Integer, Integer>(27, 6),
        new SimpleEntry<Integer, Integer>(27, 7)
      )
    ),
    // Road map 4
    Arrays.asList(
      // South
      Arrays.asList(
        new SimpleEntry<Integer, Integer>(1, 7),
        new SimpleEntry<Integer, Integer>(1, 8),
        new SimpleEntry<Integer, Integer>(1, 9),
        new SimpleEntry<Integer, Integer>(1, 10),
        new SimpleEntry<Integer, Integer>(1, 11),
        new SimpleEntry<Integer, Integer>(1, 12),
        new SimpleEntry<Integer, Integer>(1, 13),
        new SimpleEntry<Integer, Integer>(2, 13),
        new SimpleEntry<Integer, Integer>(3, 13),
        new SimpleEntry<Integer, Integer>(3, 12),
        new SimpleEntry<Integer, Integer>(3, 11),
        new SimpleEntry<Integer, Integer>(3, 10),
        new SimpleEntry<Integer, Integer>(3, 9),
        new SimpleEntry<Integer, Integer>(3, 8),
        new SimpleEntry<Integer, Integer>(3, 7),
        new SimpleEntry<Integer, Integer>(3, 6),
        new SimpleEntry<Integer, Integer>(3, 5),
        new SimpleEntry<Integer, Integer>(3, 4),
        new SimpleEntry<Integer, Integer>(4, 4),
        new SimpleEntry<Integer, Integer>(5, 4),
        new SimpleEntry<Integer, Integer>(5, 5),
        new SimpleEntry<Integer, Integer>(5, 6),
        new SimpleEntry<Integer, Integer>(5, 7),
        new SimpleEntry<Integer, Integer>(5, 8),
        new SimpleEntry<Integer, Integer>(5, 9),
        new SimpleEntry<Integer, Integer>(5, 10),
        new SimpleEntry<Integer, Integer>(5, 11),
        new SimpleEntry<Integer, Integer>(5, 12),
        new SimpleEntry<Integer, Integer>(5, 13),
        new SimpleEntry<Integer, Integer>(6, 13),
        new SimpleEntry<Integer, Integer>(7, 13),
        new SimpleEntry<Integer, Integer>(7, 12),
        new SimpleEntry<Integer, Integer>(7, 11),
        new SimpleEntry<Integer, Integer>(7, 10),
        new SimpleEntry<Integer, Integer>(7, 9),
        new SimpleEntry<Integer, Integer>(7, 8),
        new SimpleEntry<Integer, Integer>(7, 7),
        new SimpleEntry<Integer, Integer>(7, 6),
        new SimpleEntry<Integer, Integer>(7, 5),
        new SimpleEntry<Integer, Integer>(7, 4),
        new SimpleEntry<Integer, Integer>(8, 4),
        new SimpleEntry<Integer, Integer>(9, 4),
        new SimpleEntry<Integer, Integer>(9, 5),
        new SimpleEntry<Integer, Integer>(9, 6),
        new SimpleEntry<Integer, Integer>(9, 7),
        new SimpleEntry<Integer, Integer>(9, 8),
        new SimpleEntry<Integer, Integer>(9, 9),
        new SimpleEntry<Integer, Integer>(9, 10),
        new SimpleEntry<Integer, Integer>(9, 11),
        new SimpleEntry<Integer, Integer>(9, 12),
        new SimpleEntry<Integer, Integer>(9, 13),
        new SimpleEntry<Integer, Integer>(10, 13),
        new SimpleEntry<Integer, Integer>(11, 13),
        new SimpleEntry<Integer, Integer>(11, 12),
        new SimpleEntry<Integer, Integer>(11, 11),
        new SimpleEntry<Integer, Integer>(11, 10),
        new SimpleEntry<Integer, Integer>(11, 9),
        new SimpleEntry<Integer, Integer>(11, 8),
        new SimpleEntry<Integer, Integer>(11, 7),
        new SimpleEntry<Integer, Integer>(11, 6),
        new SimpleEntry<Integer, Integer>(11, 5),
        new SimpleEntry<Integer, Integer>(11, 4),
        new SimpleEntry<Integer, Integer>(12, 4),
        new SimpleEntry<Integer, Integer>(13, 4),
        new SimpleEntry<Integer, Integer>(13, 5),
        new SimpleEntry<Integer, Integer>(13, 6),
        new SimpleEntry<Integer, Integer>(13, 7),
        new SimpleEntry<Integer, Integer>(13, 8),
        new SimpleEntry<Integer, Integer>(13, 9),
        new SimpleEntry<Integer, Integer>(13, 10),
        new SimpleEntry<Integer, Integer>(13, 11),
        new SimpleEntry<Integer, Integer>(13, 12),
        new SimpleEntry<Integer, Integer>(13, 13),
        new SimpleEntry<Integer, Integer>(14, 13),
        new SimpleEntry<Integer, Integer>(15, 13),
        new SimpleEntry<Integer, Integer>(15, 12),
        new SimpleEntry<Integer, Integer>(15, 11),
        new SimpleEntry<Integer, Integer>(15, 10),
        new SimpleEntry<Integer, Integer>(15, 9),
        new SimpleEntry<Integer, Integer>(15, 8),
        new SimpleEntry<Integer, Integer>(15, 7),
        new SimpleEntry<Integer, Integer>(15, 6),
        new SimpleEntry<Integer, Integer>(15, 5),
        new SimpleEntry<Integer, Integer>(15, 4),
        new SimpleEntry<Integer, Integer>(16, 4),
        new SimpleEntry<Integer, Integer>(17, 4),
        new SimpleEntry<Integer, Integer>(17, 5),
        new SimpleEntry<Integer, Integer>(17, 6),
        new SimpleEntry<Integer, Integer>(17, 7),
        new SimpleEntry<Integer, Integer>(17, 8),
        new SimpleEntry<Integer, Integer>(17, 9),
        new SimpleEntry<Integer, Integer>(17, 10),
        new SimpleEntry<Integer, Integer>(17, 11),
        new SimpleEntry<Integer, Integer>(17, 12),
        new SimpleEntry<Integer, Integer>(17, 13),
        new SimpleEntry<Integer, Integer>(18, 13),
        new SimpleEntry<Integer, Integer>(19, 13),
        new SimpleEntry<Integer, Integer>(19, 12),
        new SimpleEntry<Integer, Integer>(19, 11),
        new SimpleEntry<Integer, Integer>(19, 10),
        new SimpleEntry<Integer, Integer>(19, 9),
        new SimpleEntry<Integer, Integer>(19, 8),
        new SimpleEntry<Integer, Integer>(19, 7),
        new SimpleEntry<Integer, Integer>(19, 6),
        new SimpleEntry<Integer, Integer>(19, 5),
        new SimpleEntry<Integer, Integer>(19, 4),
        new SimpleEntry<Integer, Integer>(20, 4),
        new SimpleEntry<Integer, Integer>(21, 4),
        new SimpleEntry<Integer, Integer>(21, 5),
        new SimpleEntry<Integer, Integer>(21, 6),
        new SimpleEntry<Integer, Integer>(21, 7),
        new SimpleEntry<Integer, Integer>(21, 8),
        new SimpleEntry<Integer, Integer>(21, 9),
        new SimpleEntry<Integer, Integer>(21, 10),
        new SimpleEntry<Integer, Integer>(21, 11),
        new SimpleEntry<Integer, Integer>(21, 12),
        new SimpleEntry<Integer, Integer>(21, 13),
        new SimpleEntry<Integer, Integer>(22, 13),
        new SimpleEntry<Integer, Integer>(23, 13),
        new SimpleEntry<Integer, Integer>(23, 12),
        new SimpleEntry<Integer, Integer>(23, 11),
        new SimpleEntry<Integer, Integer>(23, 10),
        new SimpleEntry<Integer, Integer>(23, 9),
        new SimpleEntry<Integer, Integer>(23, 8),
        new SimpleEntry<Integer, Integer>(23, 7),
        new SimpleEntry<Integer, Integer>(23, 6),
        new SimpleEntry<Integer, Integer>(23, 5),
        new SimpleEntry<Integer, Integer>(23, 4),
        new SimpleEntry<Integer, Integer>(24, 4),
        new SimpleEntry<Integer, Integer>(25, 4),
        new SimpleEntry<Integer, Integer>(25, 5),
        new SimpleEntry<Integer, Integer>(25, 6),
        new SimpleEntry<Integer, Integer>(25, 7),
        new SimpleEntry<Integer, Integer>(25, 8),
        new SimpleEntry<Integer, Integer>(25, 9),
        new SimpleEntry<Integer, Integer>(25, 10),
        new SimpleEntry<Integer, Integer>(25, 11),
        new SimpleEntry<Integer, Integer>(25, 12),
        new SimpleEntry<Integer, Integer>(25, 13),
        new SimpleEntry<Integer, Integer>(26, 13),
        new SimpleEntry<Integer, Integer>(27, 13),
        new SimpleEntry<Integer, Integer>(27, 12),
        new SimpleEntry<Integer, Integer>(27, 11),
        new SimpleEntry<Integer, Integer>(27, 10),
        new SimpleEntry<Integer, Integer>(27, 9),
        new SimpleEntry<Integer, Integer>(27, 8),
        new SimpleEntry<Integer, Integer>(27, 7),
        new SimpleEntry<Integer, Integer>(28, 7)
      ),
      // North
      Arrays.asList(
        new SimpleEntry<Integer, Integer>(1, 7),
        new SimpleEntry<Integer, Integer>(1, 6),
        new SimpleEntry<Integer, Integer>(1, 5),
        new SimpleEntry<Integer, Integer>(1, 4),
        new SimpleEntry<Integer, Integer>(1, 3),
        new SimpleEntry<Integer, Integer>(1, 2),
        new SimpleEntry<Integer, Integer>(2, 2),
        new SimpleEntry<Integer, Integer>(3, 2),
        new SimpleEntry<Integer, Integer>(3, 2),
        new SimpleEntry<Integer, Integer>(5, 2),
        new SimpleEntry<Integer, Integer>(6, 2),
        new SimpleEntry<Integer, Integer>(7, 2),
        new SimpleEntry<Integer, Integer>(8, 2),
        new SimpleEntry<Integer, Integer>(9, 2),
        new SimpleEntry<Integer, Integer>(10, 2),
        new SimpleEntry<Integer, Integer>(11, 2),
        new SimpleEntry<Integer, Integer>(12, 2),
        new SimpleEntry<Integer, Integer>(13, 2),
        new SimpleEntry<Integer, Integer>(14, 2),
        new SimpleEntry<Integer, Integer>(15, 2),
        new SimpleEntry<Integer, Integer>(16, 2),
        new SimpleEntry<Integer, Integer>(17, 2),
        new SimpleEntry<Integer, Integer>(18, 2),
        new SimpleEntry<Integer, Integer>(19, 2),
        new SimpleEntry<Integer, Integer>(20, 2),
        new SimpleEntry<Integer, Integer>(21, 2),
        new SimpleEntry<Integer, Integer>(22, 2),
        new SimpleEntry<Integer, Integer>(23, 2),
        new SimpleEntry<Integer, Integer>(24, 2),
        new SimpleEntry<Integer, Integer>(25, 2),
        new SimpleEntry<Integer, Integer>(26, 2),
        new SimpleEntry<Integer, Integer>(27, 2),
        new SimpleEntry<Integer, Integer>(27, 2),
        new SimpleEntry<Integer, Integer>(27, 3),
        new SimpleEntry<Integer, Integer>(27, 4),
        new SimpleEntry<Integer, Integer>(27, 5),
        new SimpleEntry<Integer, Integer>(27, 6),
        new SimpleEntry<Integer, Integer>(27, 7),
        new SimpleEntry<Integer, Integer>(28, 7)
      )
    ),
    // Road map 5
    Arrays.asList(
      Arrays.asList(
        new SimpleEntry<Integer, Integer>(1, 14),
        new SimpleEntry<Integer, Integer>(1, 13),
        new SimpleEntry<Integer, Integer>(1, 12),
        new SimpleEntry<Integer, Integer>(1, 11),
        new SimpleEntry<Integer, Integer>(1, 10),
        new SimpleEntry<Integer, Integer>(1, 9),
        new SimpleEntry<Integer, Integer>(1, 8),
        new SimpleEntry<Integer, Integer>(1, 7),
        new SimpleEntry<Integer, Integer>(1, 6),
        new SimpleEntry<Integer, Integer>(1, 5),
        new SimpleEntry<Integer, Integer>(1, 4),
        new SimpleEntry<Integer, Integer>(1, 3),
        new SimpleEntry<Integer, Integer>(1, 2),
        new SimpleEntry<Integer, Integer>(2, 2),
        new SimpleEntry<Integer, Integer>(3, 2),
        new SimpleEntry<Integer, Integer>(3, 2),
        new SimpleEntry<Integer, Integer>(5, 2),
        new SimpleEntry<Integer, Integer>(6, 2),
        new SimpleEntry<Integer, Integer>(7, 2),
        new SimpleEntry<Integer, Integer>(8, 2),
        new SimpleEntry<Integer, Integer>(9, 2),
        new SimpleEntry<Integer, Integer>(10, 2),
        new SimpleEntry<Integer, Integer>(11, 2),
        new SimpleEntry<Integer, Integer>(12, 2),
        new SimpleEntry<Integer, Integer>(13, 2),
        new SimpleEntry<Integer, Integer>(14, 2),
        new SimpleEntry<Integer, Integer>(15, 2),
        new SimpleEntry<Integer, Integer>(16, 2),
        new SimpleEntry<Integer, Integer>(17, 2),
        new SimpleEntry<Integer, Integer>(18, 2),
        new SimpleEntry<Integer, Integer>(19, 2),
        new SimpleEntry<Integer, Integer>(20, 2),
        new SimpleEntry<Integer, Integer>(21, 2),
        new SimpleEntry<Integer, Integer>(22, 2),
        new SimpleEntry<Integer, Integer>(23, 2),
        new SimpleEntry<Integer, Integer>(24, 2),
        new SimpleEntry<Integer, Integer>(25, 2),
        new SimpleEntry<Integer, Integer>(26, 2),
        new SimpleEntry<Integer, Integer>(27, 2),
        new SimpleEntry<Integer, Integer>(27, 2),
        new SimpleEntry<Integer, Integer>(27, 3),
        new SimpleEntry<Integer, Integer>(27, 4),
        new SimpleEntry<Integer, Integer>(27, 5),
        new SimpleEntry<Integer, Integer>(27, 6),
        new SimpleEntry<Integer, Integer>(27, 7),
        new SimpleEntry<Integer, Integer>(27, 8),
        new SimpleEntry<Integer, Integer>(27, 9),
        new SimpleEntry<Integer, Integer>(27, 10),
        new SimpleEntry<Integer, Integer>(27, 11),
        new SimpleEntry<Integer, Integer>(27, 12),
        new SimpleEntry<Integer, Integer>(27, 13),
        new SimpleEntry<Integer, Integer>(27, 14),
        new SimpleEntry<Integer, Integer>(26, 14),
        new SimpleEntry<Integer, Integer>(25, 14),
        new SimpleEntry<Integer, Integer>(24, 14),
        new SimpleEntry<Integer, Integer>(23, 14),
        new SimpleEntry<Integer, Integer>(22, 14),
        new SimpleEntry<Integer, Integer>(21, 14),
        new SimpleEntry<Integer, Integer>(20, 14),
        new SimpleEntry<Integer, Integer>(19, 14),
        new SimpleEntry<Integer, Integer>(18, 14),
        new SimpleEntry<Integer, Integer>(17, 14),
        new SimpleEntry<Integer, Integer>(16, 14),
        new SimpleEntry<Integer, Integer>(15, 14),
        new SimpleEntry<Integer, Integer>(14, 14),
        new SimpleEntry<Integer, Integer>(13, 14),
        new SimpleEntry<Integer, Integer>(12, 14),
        new SimpleEntry<Integer, Integer>(11, 14),
        new SimpleEntry<Integer, Integer>(10, 14),
        new SimpleEntry<Integer, Integer>(9, 14),
        new SimpleEntry<Integer, Integer>(8, 14),
        new SimpleEntry<Integer, Integer>(7, 14),
        new SimpleEntry<Integer, Integer>(6, 14),
        new SimpleEntry<Integer, Integer>(5, 14),
        new SimpleEntry<Integer, Integer>(4, 14),
        new SimpleEntry<Integer, Integer>(3, 14),
        new SimpleEntry<Integer, Integer>(3, 13),
        new SimpleEntry<Integer, Integer>(3, 12),
        new SimpleEntry<Integer, Integer>(3, 11),
        new SimpleEntry<Integer, Integer>(3, 10),
        new SimpleEntry<Integer, Integer>(3, 9),
        new SimpleEntry<Integer, Integer>(3, 8),
        new SimpleEntry<Integer, Integer>(3, 7),
        new SimpleEntry<Integer, Integer>(3, 6),
        new SimpleEntry<Integer, Integer>(3, 5),
        new SimpleEntry<Integer, Integer>(3, 4),
        new SimpleEntry<Integer, Integer>(4, 4),
        new SimpleEntry<Integer, Integer>(5, 4),
        new SimpleEntry<Integer, Integer>(6, 4),
        new SimpleEntry<Integer, Integer>(7, 4),
        new SimpleEntry<Integer, Integer>(8, 4),
        new SimpleEntry<Integer, Integer>(9, 4),
        new SimpleEntry<Integer, Integer>(10, 4),
        new SimpleEntry<Integer, Integer>(11, 4),
        new SimpleEntry<Integer, Integer>(12, 4),
        new SimpleEntry<Integer, Integer>(13, 4),
        new SimpleEntry<Integer, Integer>(14, 4),
        new SimpleEntry<Integer, Integer>(15, 4),
        new SimpleEntry<Integer, Integer>(16, 4),
        new SimpleEntry<Integer, Integer>(17, 4),
        new SimpleEntry<Integer, Integer>(18, 4),
        new SimpleEntry<Integer, Integer>(19, 4),
        new SimpleEntry<Integer, Integer>(20, 4),
        new SimpleEntry<Integer, Integer>(21, 4),
        new SimpleEntry<Integer, Integer>(22, 4),
        new SimpleEntry<Integer, Integer>(23, 4),
        new SimpleEntry<Integer, Integer>(24, 4),
        new SimpleEntry<Integer, Integer>(25, 4),
        new SimpleEntry<Integer, Integer>(25, 5),
        new SimpleEntry<Integer, Integer>(25, 6),
        new SimpleEntry<Integer, Integer>(25, 7),
        new SimpleEntry<Integer, Integer>(25, 8),
        new SimpleEntry<Integer, Integer>(25, 9),
        new SimpleEntry<Integer, Integer>(25, 10),
        new SimpleEntry<Integer, Integer>(25, 11),
        new SimpleEntry<Integer, Integer>(25, 12),
        new SimpleEntry<Integer, Integer>(24, 12),
        new SimpleEntry<Integer, Integer>(23, 12),
        new SimpleEntry<Integer, Integer>(22, 12),
        new SimpleEntry<Integer, Integer>(21, 12),
        new SimpleEntry<Integer, Integer>(20, 12),
        new SimpleEntry<Integer, Integer>(19, 12),
        new SimpleEntry<Integer, Integer>(18, 12),
        new SimpleEntry<Integer, Integer>(17, 12),
        new SimpleEntry<Integer, Integer>(16, 12),
        new SimpleEntry<Integer, Integer>(15, 12),
        new SimpleEntry<Integer, Integer>(14, 12),
        new SimpleEntry<Integer, Integer>(13, 12),
        new SimpleEntry<Integer, Integer>(12, 12),
        new SimpleEntry<Integer, Integer>(11, 12),
        new SimpleEntry<Integer, Integer>(10, 12),
        new SimpleEntry<Integer, Integer>(9, 12),
        new SimpleEntry<Integer, Integer>(8, 12),
        new SimpleEntry<Integer, Integer>(7, 12),
        new SimpleEntry<Integer, Integer>(6, 12),
        new SimpleEntry<Integer, Integer>(5, 12),
        new SimpleEntry<Integer, Integer>(5, 11),
        new SimpleEntry<Integer, Integer>(5, 10),
        new SimpleEntry<Integer, Integer>(5, 9),
        new SimpleEntry<Integer, Integer>(5, 8),
        new SimpleEntry<Integer, Integer>(5, 7),
        new SimpleEntry<Integer, Integer>(5, 6),
        new SimpleEntry<Integer, Integer>(6, 6),
        new SimpleEntry<Integer, Integer>(7, 6),
        new SimpleEntry<Integer, Integer>(8, 6),
        new SimpleEntry<Integer, Integer>(9, 6),
        new SimpleEntry<Integer, Integer>(10, 6),
        new SimpleEntry<Integer, Integer>(11, 6),
        new SimpleEntry<Integer, Integer>(12, 6),
        new SimpleEntry<Integer, Integer>(13, 6),
        new SimpleEntry<Integer, Integer>(14, 6),
        new SimpleEntry<Integer, Integer>(15, 6),
        new SimpleEntry<Integer, Integer>(16, 6),
        new SimpleEntry<Integer, Integer>(17, 6),
        new SimpleEntry<Integer, Integer>(18, 6),
        new SimpleEntry<Integer, Integer>(19, 6),
        new SimpleEntry<Integer, Integer>(20, 6),
        new SimpleEntry<Integer, Integer>(21, 6),
        new SimpleEntry<Integer, Integer>(22, 6),
        new SimpleEntry<Integer, Integer>(23, 6),
        new SimpleEntry<Integer, Integer>(23, 7),
        new SimpleEntry<Integer, Integer>(23, 8),
        new SimpleEntry<Integer, Integer>(23, 9),
        new SimpleEntry<Integer, Integer>(23, 10),
        new SimpleEntry<Integer, Integer>(22, 10),
        new SimpleEntry<Integer, Integer>(21, 10),
        new SimpleEntry<Integer, Integer>(20, 10),
        new SimpleEntry<Integer, Integer>(19, 10),
        new SimpleEntry<Integer, Integer>(18, 10),
        new SimpleEntry<Integer, Integer>(17, 10),
        new SimpleEntry<Integer, Integer>(16, 10),
        new SimpleEntry<Integer, Integer>(15, 10),
        new SimpleEntry<Integer, Integer>(14, 10),
        new SimpleEntry<Integer, Integer>(13, 10),
        new SimpleEntry<Integer, Integer>(12, 10),
        new SimpleEntry<Integer, Integer>(11, 10),
        new SimpleEntry<Integer, Integer>(10, 10),
        new SimpleEntry<Integer, Integer>(9, 10),
        new SimpleEntry<Integer, Integer>(8, 10),
        new SimpleEntry<Integer, Integer>(7, 10),
        new SimpleEntry<Integer, Integer>(7, 9),
        new SimpleEntry<Integer, Integer>(7, 8),
        new SimpleEntry<Integer, Integer>(8, 8),
        new SimpleEntry<Integer, Integer>(9, 8),
        new SimpleEntry<Integer, Integer>(10, 8),
        new SimpleEntry<Integer, Integer>(11, 8),
        new SimpleEntry<Integer, Integer>(12, 8),
        new SimpleEntry<Integer, Integer>(13, 8),
        new SimpleEntry<Integer, Integer>(14, 8),
        new SimpleEntry<Integer, Integer>(15, 8),
        new SimpleEntry<Integer, Integer>(16, 8),
        new SimpleEntry<Integer, Integer>(17, 8),
        new SimpleEntry<Integer, Integer>(18, 8),
        new SimpleEntry<Integer, Integer>(19, 8),
        new SimpleEntry<Integer, Integer>(20, 8),
        new SimpleEntry<Integer, Integer>(21, 8)
      )
    )
  );

  public Level(Game game) {
    setBackground(Color.BLACK);

    for (int i = 1; i <= 5; i++) {
      JButton levelButton = new JButton("Level " + i);
      int finalI = i;

      levelButton.addActionListener(
        new ActionListener() {
          public void actionPerformed(ActionEvent e) {
            PlayPage playPage = new PlayPage(
              game,
              LEVEL_MAPS[finalI - 1],
              ROUTES.get(finalI - 1)
            );
            game.setContentPane(playPage);
            game.revalidate();
            game.repaint();
          }
        }
      );
      add(levelButton);
    }
  }
}
